### ISSUE TITLE
Can it run on 32-bit Ubuntu?

### ISSUE THREAD

**Issue by jkleiser** [BlackBoxCenter/blackbox#85]
Can this BlackBox be used on 32-bit Ubuntu (ubuntu-14.04.3-desktop-i386.iso)? It seems Ubuntu recommends the 32-bit version on machines with less than 2GB RAM. My old Mac mini has only 1GB, but I haven't installed Ubuntu yet.

**Comment by diamagnetic** [comment]
Yes, it can be run on Ubuntu after installing Wine.
```sudo apt-get install wine```
Also I recommend you to tune up fonts. Run Wine Config application from Dash and select good fonts for menu etc.
You can download last BlackBox build from:
http://blackboxframework.org/lastdev/zip.php

Also you can run experimental version for Linux. First install some dependencies:
```sudo apt-get install libgtk2.0-0 gtk2-engines gtk2-engines-murrine libcanberra-gtk-module libgnomeui-0```
then download and install debian package:
http://oberon.molpit.com/packs/bbcb_1.7-a1-4_i386.deb

**Comment by jtempl** [comment]
I have added this information to our Wiki at http://wiki.blackboxframework.org/index.php?title=Running_BlackBox_under_Linux

**Comment by jkleiser** [comment]
Thanks. I managed to download and run the Wine BlackBox. I also managed to install dependencies and download the Debian package (on my fresh 32-bit Ubuntu), but I haven't yet figured out how to run it. Anyway, this is great fun.

**Comment by diamagnetic** [comment]
To run Linux version of BlackBox go to Dash and type BlackBox there. You will see the yellow puzzle icon. Also you can run it by the command ```bbcb``` from the Terminal.

**Comment by jkleiser** [comment]
Sorry, I am a Ubuntu newbie, and I do not know what Dash is. Also, my Debian BlackBox may not be properly installed. I found the bbcb in ~/BlackBox/bbcb_1.7-a1-4_i386/usr/bin, but when I try ./bbcb, I get this:
env: /usr/lib/blackbox/blackbox: No such file or directory

**Comment by diamagnetic** [comment]
It seems that you did not install the package proper way. Just click on the .deb package twice to install it with a help of Ubuntu Software Center or run ```sudo dpkg -i bbcb_1.7-a1-4_i386``` in Terminal. Dash is main menu to run applications in a Unity interface of Ubuntu.

**Comment by jkleiser** [comment]
The "sudo dpkg" alternative worked. The first time I did bbcb, I got an error message like "Error 04 ... wrong fingerprint", but the next time it worked better. One problem I noticed, was when I tried the Obx->Primes. It was not possible to enter any number for the upper limit.
I now plan to switch from my current 32-bit Ubuntu to a 64-bit Lubuntu that will probably be better suited for my old Mac mini with only 1GB RAM. I look forward to do more BBCB testing later.

**Comment by diamagnetic** [comment]
If Ubuntu works slow with your configuration, you can try Xubuntu. This is lightweight version with Xfce interface system. It can run with even with 512 MB RAM.

First error you get because you tried to run ```bbcb``` in the directory with Windows version of Blackbox. In this case it catch incompatible code files from this directory.

In Linux version the interface like Edit Fields is not working well yet. Only the text interface is well fitted. So for learning is better to use Windows version with Wine.

**Comment by diamagnetic** [comment]
Also I want to mention, that this issues tracker is for windows version only. We have separate issue tracker for Linux prototype http://gitlab.molpit.org/oberon/blackbox-freenix/issues
